/* AUTO-GENERATED by dump_moonshine_reference.py — do not edit. */
#ifndef MOONSHINE_REFERENCE_H
#define MOONSHINE_REFERENCE_H

#define MS_REF_AUDIO_SAMPLES 48000
#define MS_REF_ENC_POSITIONS 123
#define MS_REF_BOS 1
#define MS_REF_EOT 2

static const int ms_ref_greedy_tokens[] = { 1126, 577, 590, 10404, 23035, 29889, 2 };
#define MS_REF_GREEDY_LEN 7

typedef struct { const char *name; double sum, absmax, mean; } ms_ref_stage_t;
static const ms_ref_stage_t ms_ref_stages[] = {
    { "pre", 2.643744299e+04, 2.766140556e+01, 7.463144475e-01 },
    { "enc0", 2.255951883e+04, 8.355950928e+01, 6.368427855e-01 },
    { "enc1", 2.146065466e+04, 1.408229218e+02, 6.058224555e-01 },
    { "enc2", 2.218887541e+04, 2.065561829e+02, 6.263797259e-01 },
    { "enc3", 2.168161697e+04, 2.267331238e+02, 6.120600996e-01 },
    { "enc4", 1.951854032e+04, 3.355794373e+02, 5.509976378e-01 },
    { "enc5", 2.062221538e+04, 2.328194336e+03, 5.821537765e-01 },
    { "enc_out", 3.944767483e+02, 6.852270603e+00, 1.113586123e-02 },
};
#define MS_REF_NUM_STAGES 8

#endif /* MOONSHINE_REFERENCE_H */
