/* AUTO-GENERATED by dump_whisper_reference.py — do not edit. */
#ifndef WHISPER_REFERENCE_H
#define WHISPER_REFERENCE_H

#define WHISPER_REF_MEL_FRAMES 200
#define WHISPER_REF_ENC_POSITIONS 100
#define WHISPER_REF_EOT 50256

static const int whisper_ref_sot_tokens[] = { 50257, 50362 };
#define WHISPER_REF_SOT_LEN 2

static const int whisper_ref_greedy_tokens[] = { 843, 523, 616, 5891, 10162, 290, 523, 616 };
#define WHISPER_REF_GREEDY_LEN 8

typedef struct { const char *name; double sum, absmax, mean; } whisper_ref_stage_t;
static const whisper_ref_stage_t whisper_ref_stages[] = {
    { "conv1", 5.045358865e+03, 4.877238750e+00, 6.569477689e-02 },
    { "conv2", 4.848009312e+03, 3.338512182e+00, 1.262502425e-01 },
    { "pos_add", 1.858707125e+04, 3.979171276e+00, 4.840383138e-01 },
    { "enc_block0", 2.221741959e+04, 3.645044327e+00, 5.785786353e-01 },
    { "enc_block1", 2.239696348e+04, 3.533737659e+00, 5.832542574e-01 },
    { "enc_block2", 2.205566596e+04, 6.827941895e+00, 5.743663011e-01 },
    { "enc_block3", 2.255340509e+04, 2.601986084e+02, 5.873282576e-01 },
    { "enc_out", 2.955104034e+02, 9.908102989e+00, 7.695583423e-03 },
};
#define WHISPER_REF_NUM_STAGES 8

#endif /* WHISPER_REFERENCE_H */
