#ifndef C2C_DSP_WHISPER_CONFIG_H
#define C2C_DSP_WHISPER_CONFIG_H

#include <stdio.h>
#include "chip_config.h"

/* ------------------------------------------------------------------------------------------------
 * dsp-whisper — Whisper tiny.en speech-to-text on DSP 25 (plan 005).
 *
 * THIS BUILD = P0 FRONT-END SCAFFOLD ONLY. Standalone (no C2C link, no I2S yet). It computes the
 * Whisper log-mel spectrogram in C on an embedded golden test vector and diffs each frame against
 * the host reference (generated by dsp25-tests/whisper-test/scripts/gen_whisper_frontend.py). This
 * isolates the front-end — historically where MFCC-style ports drift — before the encoder/decoder
 * engine is written. See .claude/plans/005-whisper-dsp.md.
 *
 * n_fft=400 is NOT a power of two, so the radix-2 NMSIS rFFT in mfcc-lib cannot be reused; the
 * front-end uses a direct DFT (precomputed cos/sin, built once at init). Correct for 400, and a
 * clean RVV target later (two dot-products per bin).
 * ---------------------------------------------------------------------------------------------- */

#ifndef DSP_WHISPER_LOG_ENABLE
#define DSP_WHISPER_LOG_ENABLE 1
#endif

#if DSP_WHISPER_LOG_ENABLE
#define DSP_WHISPER_LOG(...) do { printf(__VA_ARGS__); } while (0)
#else
#define DSP_WHISPER_LOG(...) do { } while (0)
#endif

/* Per-value abs tolerance for the log-mel front-end diff vs the host golden. The C DFT accumulates
 * in float32 over 400 taps vs torch's float32 FFT, so tiny differences are expected; log10 is
 * stable for the large mel energies that matter. Tighten once measured on silicon. */
#ifndef DSP_WHISPER_LOGMEL_TOL
#define DSP_WHISPER_LOGMEL_TOL 0.05f
#endif

/* How many leading mel coefficients of frame 0 to print for eyeballing against the host. */
#ifndef DSP_WHISPER_PREVIEW_COEFFS
#define DSP_WHISPER_PREVIEW_COEFFS 8
#endif

/* ---- Run modes (mutually exclusive with the default embedded-golden-mel validate mode) --------
 * DSP_WHISPER_FROM_AUDIO : transcribe the embedded audio blob (Spike-testable; validates the full
 *                          on-device audio -> log-mel -> encode -> decode path, no I2S).
 * DSP_WHISPER_USE_MIC    : capture live audio from the I2S mic (VAD-gated) and transcribe in a loop.
 *                          Real silicon only (Spike has no I2S). Build PLATFORM=CHIP. */
#ifndef DSP_WHISPER_FROM_AUDIO
#define DSP_WHISPER_FROM_AUDIO 0
#endif
#ifndef DSP_WHISPER_USE_MIC
#define DSP_WHISPER_USE_MIC 0
#endif

/* Max encoder frames the transcribe buffer holds (n_frames = samples/160). 400 = 4 s. */
#ifndef DSP_WHISPER_MAX_FRAMES
#define DSP_WHISPER_MAX_FRAMES 400
#endif
/* Max decoded tokens per utterance. */
#ifndef DSP_WHISPER_MAX_TOKENS
#define DSP_WHISPER_MAX_TOKENS 96
#endif

/* Operating frequency the PLL is set to by init_test (mic build). 750 MHz for more throughput; dial
 * back to 500e6 if the PLL doesn't lock / the chip is unstable. UART divisor tracks this automatically. */
#ifndef DSP_WHISPER_TARGET_FREQ_HZ
#define DSP_WHISPER_TARGET_FREQ_HZ 750000000ULL
#endif

/* ---- I2S mic capture (mirrors the proven dsp-kws-rolling mic path) ---------------------------- */
#ifndef DSP_WHISPER_MIC_CHANNEL
#define DSP_WHISPER_MIC_CHANNEL 0
#endif
#ifndef DSP_WHISPER_MIC_SAMPLE_RATE_HZ
#define DSP_WHISPER_MIC_SAMPLE_RATE_HZ 16000u
#endif
#ifndef DSP_WHISPER_MIC_BITDEPTH
#define DSP_WHISPER_MIC_BITDEPTH 32u
#endif
/* Capture window in samples (16000 = 1 s @ 16 kHz). Must be <= DSP_WHISPER_MAX_FRAMES*160. */
#ifndef DSP_WHISPER_MIC_NUM_SAMPLES
#define DSP_WHISPER_MIC_NUM_SAMPLES 32000u
#endif
#ifndef DSP_WHISPER_MIC_SAMPLE_SHIFT
#define DSP_WHISPER_MIC_SAMPLE_SHIFT 8            /* 24-bit sample in top of the 32-bit slot */
#endif
#ifndef DSP_WHISPER_MIC_FULLSCALE
#define DSP_WHISPER_MIC_FULLSCALE 8388608.0f      /* 2^23 */
#endif
/* VAD onset gate (short-frame AC energy) + pre-roll, identical scheme to dsp-kws-rolling. */
#ifndef DSP_WHISPER_VAD_ENABLE
#define DSP_WHISPER_VAD_ENABLE 1
#endif
#ifndef DSP_WHISPER_VAD_FRAME_SAMPLES
#define DSP_WHISPER_VAD_FRAME_SAMPLES 320u
#endif
#ifndef DSP_WHISPER_VAD_PREROLL_SAMPLES
#define DSP_WHISPER_VAD_PREROLL_SAMPLES 3200u
#endif
/* Onset threshold (raised — rejects room noise; tune from the logged per-frame energy). */
#ifndef DSP_WHISPER_VAD_THRESHOLD
#define DSP_WHISPER_VAD_THRESHOLD 1.5e-3f
#endif
#ifndef DSP_WHISPER_VAD_LOG_EVERY
#define DSP_WHISPER_VAD_LOG_EVERY 25u
#endif
/* End-of-speech detection: stop capturing once energy stays below END_THRESHOLD for HANGOVER frames.
 * DISABLED by default: it was cutting after the first ~300 ms inter-word gap, so the encoder only saw
 * a fraction of a word and Whisper collapsed to a repeated token. Whisper is trained on 30 s windows
 * zero-padded, so trailing silence is harmless — capturing a FIXED ~2 s window after onset is far more
 * robust than aggressive end-cutting. Re-enable (with a long HANGOVER) only if latency demands it. */
#ifndef DSP_WHISPER_VAD_END_ENABLE
#define DSP_WHISPER_VAD_END_ENABLE 0
#endif
#ifndef DSP_WHISPER_VAD_END_THRESHOLD
#define DSP_WHISPER_VAD_END_THRESHOLD 8.0e-4f
#endif
#ifndef DSP_WHISPER_VAD_HANGOVER_FRAMES
#define DSP_WHISPER_VAD_HANGOVER_FRAMES 40u   /* ~800 ms of silence at 320-sample (20 ms) frames */
#endif
#ifndef DSP_WHISPER_VAD_MIN_SAMPLES
#define DSP_WHISPER_VAD_MIN_SAMPLES 24000u    /* >= 1.5 s captured before end-detect can fire */
#endif

#endif /* C2C_DSP_WHISPER_CONFIG_H */
