/* Generated by c2c-demos/bearly-smollm/scripts/ref_runq.py --golden. Do not edit.
 * Sum of the residual stream after each stage of forward(token=1, pos=0), from the
 * host reference. SMOLLM_DEBUG_GOLDEN=1 makes the device print the same sums, so a
 * mismatch localizes the diverging layer instead of just "the output is wrong". */
#ifndef SMOLLM_GOLDEN_H
#define SMOLLM_GOLDEN_H

#define SMOLLM_GOLDEN_TOKEN 1
#define SMOLLM_GOLDEN_STAGES 32

static const float g_smollm_golden_sums[SMOLLM_GOLDEN_STAGES] = {
  3.409203e-01f,  /* embed */
  -2.606966e+01f,  /* layer0 */
  2.404896e+02f,  /* layer1 */
  5.651129e+02f,  /* layer2 */
  5.416162e+02f,  /* layer3 */
  5.390997e+02f,  /* layer4 */
  5.318827e+02f,  /* layer5 */
  5.222365e+02f,  /* layer6 */
  5.180690e+02f,  /* layer7 */
  4.968847e+02f,  /* layer8 */
  1.461035e+02f,  /* layer9 */
  2.677211e+02f,  /* layer10 */
  2.791134e+04f,  /* layer11 */
  2.790918e+04f,  /* layer12 */
  2.791783e+04f,  /* layer13 */
  2.790994e+04f,  /* layer14 */
  2.789250e+04f,  /* layer15 */
  2.787015e+04f,  /* layer16 */
  2.785967e+04f,  /* layer17 */
  2.783852e+04f,  /* layer18 */
  2.781282e+04f,  /* layer19 */
  2.780771e+04f,  /* layer20 */
  2.784085e+04f,  /* layer21 */
  2.787179e+04f,  /* layer22 */
  2.788678e+04f,  /* layer23 */
  2.802730e+04f,  /* layer24 */
  2.804819e+04f,  /* layer25 */
  2.804575e+04f,  /* layer26 */
  2.872759e+04f,  /* layer27 */
  1.388525e+04f,  /* layer28 */
  1.045888e+04f,  /* layer29 */
  3.976645e+05f,  /* logits */
};

#endif /* SMOLLM_GOLDEN_H */
